apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yvpe6h8wz-go
  janus-idp.io/tekton: yvpe6h8wz-go
  backstage.io/kubernetes-id: yvpe6h8wz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yvpe6h8wz-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
